# Read config documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go test ./...
builds:
  - main: ./cmd/temporalite
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - id: "temporalite"
    image_templates:
      - "ghcr.io/dacsang97/temporalite:{{ .Tag }}"
      - "ghcr.io/dacsang97/temporalite:latest"
    dockerfile: ./build/Dockerfile
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
